name: Build
on: [push, pull_request]
jobs:
  build-example-ios:
    name: build-example-ios
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Install example
        run: yarn bootstrap
      - name: Build
        run: cd example/ios && xcodebuild -workspace CameraKitExample.xcworkspace -configuration Debug -scheme CameraKitExample -sdk iphoneos build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  build-example-android:
    name: build-example-android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Install modules
        run: yarn
      - name: Install example
        run: yarn bootstrap
      - name: Build
        run: cd example/android && ./gradlew assembleDebug
